version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    
    depends_on:
      - db
    volumes:
      - .:/var/www/html


  npm:
    image: node:16
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    environment:
      - NODE_ENV=development
      
    command: ["npm", "run", "dev"]
    
    depends_on:
      - app


        
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      # MYSQL_DATABASE: laravel
      # DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: admin
      DB_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
