version: '3'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - 33061:3306  
    volumes:
      - db:/var/lib/mysql
volumes:
  db: